### ISSUE TITLE
error when execute python server.py

### ISSUE THREAD

**Issue by StepIg** [fsahin/artist-explorer#22]
on windows, all is running ok until i run server.py
i got this error
can someone give any help?
thanks in advance

Traceback (most recent call last):
  File "server.py", line 12, in <module>
    import spotipy
  File "X:\Python\Python37\lib\site-packages\spotipy\__init__.py", line 2, in <module>
    from client import Spotify, SpotifyException
ModuleNotFoundError: No module named 'client'

**Comment by StepIg** [comment]
Problem is with python v3
Solved with python v.2.7.15
